baseURL: https://benmezger.github.io/
languageCode: en-us
title: Ben Mezger
theme: book
enableRobotsTXT: true
disqusShortname: benmezger
googleAnalytics: UA-138318350-1

enableGitInfo: 1
enableEmoji: true

# Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

languages:
  en:
    languageName: English
    contentDir: content
    weight: 1
#  pt:
#    languageName: Portuguese
#    contentDir: content.pt
#    weight: 1

params:
  BookServiceWorker: true
  BookToC: true
  BookMenuBundle: /menu
  BookSection: blog
  BookSearch: true
  BookRepo: https://github.com/benmezger/blog
  BookEditPath: edit/main
  BookTheme: auto
